### ISSUE TITLE
Autoprefixing and stacking browser-specific pseudo-selectors

### ISSUE THREAD

**Issue by FranzSkuffka** [jenius/autoprefixer-stylus#16]
http://stackoverflow.com/questions/2610497/change-an-inputs-html5-placeholder-color-with-css

convert

*:input-placeholder {
    color: red;
}

to

*::-webkit-input-placeholder {
    color: red;
}
*:-moz-placeholder {
    /* FF 4-18 */
    color: red;
}
*::-moz-placeholder {
    /* FF 19+ */
    color: red;
}
*:-ms-input-placeholder {
    /* IE 10+ */
    color: red;
}

**Comment by jenius** [comment]
This library is not autoprefixer, it's just a stylus wrapper for it. If you have questions or issues with the behavior of autoprefixer itself, you should ask them in its repo, which [can be found here](https://github.com/postcss/autoprefixer)

**Comment by FranzSkuffka** [comment]
Next time i should also look through the deps, not only the devDeps, i'm sorry.

**Comment by jenius** [comment]
It's ok, no worries! Appreciate the suggestions either way, that's an easy thing to overlook :grinning:
