### ISSUE TITLE
When using autoprefixer-stylus with gulp-stylus and trying to generate inline source maps file property is missing.

### ISSUE THREAD

**Issue by mareksuscak** [jenius/autoprefixer-stylus#18]
Hey guys, sorry for creating multiple issues in different projects but I don't know where's the problem exactly. So could you take a look at azu/multi-stage-sourcemap#3 please?

**Comment by jenius** [comment]
Already discussed here: https://github.com/jenius/autoprefixer-stylus/issues/17

It's an issue with gulp. I'll try to get this worked out eventually. For now, you can use gulp-autoprefixer instead and people have reported that it works fine.
