### ISSUE TITLE
browserslist file?

### ISSUE THREAD

**Issue by JSteunou** [jenius/autoprefixer-stylus#20]
I tried this stylus plugin but I cannot succeed to make it use my browserslist file.

If I'm using stylus then autoprefixer as 2 distinct commands it works very well. But a one liner with autoprefixer-stylus uses default browsers config instead of my browserslist file.

Am I missing something?

**Comment by JSteunou** [comment]
Think I just find out. You're using 4.x and this feature is from 5.x

**Comment by ai** [comment]
Seems like maintainer forgot about project. It still uses Autoprefixer 4, but we already had Autoprefixer 5 for a year.

I recommend you to run Autoprefixer by gulp-postcss.

**Comment by JSteunou** [comment]
@ai for tiny projects I use npm scripts which is very useful & lighter than using grunt / gulp
