### ISSUE TITLE
Autoprefixing Flexbox

### ISSUE THREAD

**Issue by arecvlohe** [jenius/autoprefixer-stylus#25]
My error is below. It is telling me to write display: flex as opposed to display: box. I am not writing display: box in my styl but when I output my file into the builds directory in css one of the autoprefixers is display: box. Below is also my gulp task for stylus, my css, and the console error. 

CSS (final output)

header {
  height: 100vh;
  background: url("/images/bigfoot.jpg") center/cover fixed;
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: box;
  display: flex;

STYL (gulp task)

var prefixer = 'autoprefixer-stylus'

gulp.task 'stylus', ->
  gulp.src 'src/styles/main.styl'
    .pipe plumber()
    .pipe stylus(
      import: [
        'nib'
      ]
      use: [
        nib(),
        prefixer(versions, {cascade: true})
      ]
      )
    .pipe gulp.dest paths.output + '/css'
    .pipe connect.reload()

ERROR

{ type: 'warning',
  text: 'You should write display: flex by final spec instead of display: box',
  node: 
   { type: 'decl',
     parent: 
      { nodes: [Object],
        type: 'rule',
        parent: [Object],
        source: [Object],
        before: '\n',
        between: ' ',
        selector: 'footer',
        semicolon: true,
        after: '\n',
        lastEach: 9,
        indexes: {},
        _autoprefixerDisabled: false,
        _autoprefixerPrefix: false },
     source: { start: [Object], input: [Object], end: [Object] },
     before: '\n  ',
     prop: 'display',
     between: ': ',
     value: 'box',
     _autoprefixerDisabled: false },

**Comment by ai** [comment]
I think error message is very clear: "You should write display: flex by final spec instead of display: box".

**Comment by arecvlohe** [comment]
In my stylus file I am not writing display: box, I am writing display: flex, but the output to my css file is display:box along with other prefixers, which I am pretty sure autoprefixer is adding.

**Comment by ai** [comment]
@avecvlohe there is no such thing as `display: box`. Use `display: flex`.

**Comment by arecvlohe** [comment]
in my stylus file i am putting flex:box but in my output css file it puts flex:box along with other prefixes. does that make sense?

**Comment by arecvlohe** [comment]
i mean i am putting display:flex, my output in css there is display: box, along with other prefixes

**Comment by ai** [comment]
@arecvlohe check other libraries, which eecuting before Autoprefixer. Maybe you have some Stylus mixins like nib?

**Comment by arecvlohe** [comment]
@ai 
Thanks for the advice! The problem was with nib, as seen here: https://github.com/tj/nib/issues/312

**Comment by jenius** [comment]
:+1: thanks for taking care of this @ai
